#!/usr/bin/env python3
"""build_index.py — deterministic wiki/index.md catalog builder (CLAUDE.md §6).

The index catalog is *generated*, not hand-maintained: every content page carries
its one-line summary in `description:` frontmatter (OKF core field), and this
script renders those verbatim into a marker-delimited region of wiki/index.md.
Hand-written prose outside the markers (the intro above, any notes below) is
preserved untouched. To change a catalog line, edit the page's `description:`
and re-run — never edit between the markers.

  * render_catalog(wiki_dir) -> the marker-delimited catalog block
  * apply(index_text, catalog) -> index_text with the region replaced; on a
    pre-marker index (first run) the region is everything from the first
    recognized category heading to EOF
  * CLI: --check (exit 1 + message on drift) | --write (rewrite in place)

Section order is fixed (Top level, Entities, Concepts, Processes, Rules,
Terminology, then any other folder title-cased); slugs alphabetical within a
section; root pages link bare ([[overview]]), foldered pages folder-qualified
([[entities/cid]]). index.md and log.md are never listed (OKF reserved files).

Importable (lint_wiki drift check, migrate_okf) and runnable via main().
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

MARKER_BEGIN = ("<!-- catalog:begin — generated by scripts/build_index.py; "
                "edit page `description:` frontmatter, not these lines -->")
MARKER_END = "<!-- catalog:end -->"
_BEGIN_PREFIX = "<!-- catalog:begin"
_END_PREFIX = "<!-- catalog:end"

NO_DESCRIPTION = "*(no description)*"

# Reserved OKF files — never catalog entries.
RESERVED = {"index", "log"}

# Fixed folder -> section mapping and order; unknown folders follow, title-cased.
_SECTIONS = (
    ("(root)", "Top level"),
    ("entities", "Entities"),
    ("concepts", "Concepts"),
    ("processes", "Processes"),
    ("rules", "Rules"),
    ("terminology", "Terminology"),
)
# Headings that mark the start of the catalog on a pre-marker index (first run).
# "Overview" is a legacy alias some wikis used for the root-pages section.
_KNOWN_HEADINGS = {title for _, title in _SECTIONS} | {"Overview"}

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
_DESC_LINE_RE = re.compile(r"^description\s*:\s*(.+)$", re.MULTILINE)


def page_description(text: str) -> str | None:
    """The page's `description:` frontmatter value, or None if absent/unparseable."""
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        fm = yaml.safe_load(m.group(1)) or {}
        desc = fm.get("description")
    except yaml.YAMLError:
        # Fall back to the raw line so one bad key elsewhere doesn't hide it.
        line = _DESC_LINE_RE.search(m.group(1))
        desc = line.group(1).strip() if line else None
    if isinstance(desc, str):
        desc = " ".join(desc.split())  # frontmatter may soft-wrap; catalog is one line
        return desc or None
    return None


def _folder(p: Path, wiki_dir: Path) -> str:
    rel = p.relative_to(wiki_dir)
    return rel.parts[0] if len(rel.parts) > 1 else "(root)"


def render_catalog(wiki_dir: Path, texts: dict[Path, str] | None = None) -> str:
    """The full marker-delimited catalog block for wiki_dir's content pages.

    `texts` optionally overrides on-disk content per path (used by migrate_okf
    to render the catalog from not-yet-written page updates in dry-run mode).
    """
    texts = texts or {}
    by_folder: dict[str, list[Path]] = {}
    for p in sorted(wiki_dir.rglob("*.md")):
        if p.stem in RESERVED:
            continue
        by_folder.setdefault(_folder(p, wiki_dir), []).append(p)

    ordered: list[tuple[str, str]] = [(f, t) for f, t in _SECTIONS if f in by_folder]
    known = {f for f, _ in _SECTIONS}
    ordered += [(f, f.replace("-", " ").title()) for f in sorted(by_folder) if f not in known]

    sections: list[str] = []
    for folder, title in ordered:
        lines = [f"## {title}"]
        for p in sorted(by_folder[folder], key=lambda p: p.stem):
            rel = p.relative_to(wiki_dir).with_suffix("")
            link = p.stem if folder == "(root)" else rel.as_posix()
            text = texts.get(p) if p in texts else p.read_text(encoding="utf-8")
            desc = page_description(text) or NO_DESCRIPTION
            lines.append(f"- [[{link}]] — {desc}")
        sections.append("\n".join(lines))
    return MARKER_BEGIN + "\n" + "\n\n".join(sections) + "\n" + MARKER_END


def _region(index_text: str) -> tuple[int, int] | None:
    """(start, end) character span of the catalog region in index_text.

    Marker pair wins; on a pre-marker index the region runs from the first
    recognized category heading to EOF. None if neither is found.
    """
    lines = index_text.splitlines(keepends=True)
    pos = 0
    begin = end = None
    first_heading = None
    for line in lines:
        stripped = line.strip()
        if begin is None and stripped.startswith(_BEGIN_PREFIX):
            begin = pos
        if stripped.startswith(_END_PREFIX):
            end = pos + len(line.rstrip("\n"))
        if (first_heading is None and stripped.startswith("## ")
                and stripped[3:].strip() in _KNOWN_HEADINGS):
            first_heading = pos
        pos += len(line)
    if begin is not None and end is not None and end > begin:
        return begin, end
    if first_heading is not None:
        return first_heading, len(index_text.rstrip("\n"))
    return None


def apply(index_text: str, catalog: str) -> str:
    """index_text with its catalog region replaced by `catalog` (appended if none)."""
    span = _region(index_text)
    if span is None:
        base = index_text.rstrip("\n")
        return (base + "\n\n" if base else "") + catalog + "\n"
    start, end = span
    return index_text[:start] + catalog + index_text[end:]


def current_region(index_text: str) -> str | None:
    """The on-disk catalog region text (marker pair or first-run wrap), or None."""
    span = _region(index_text)
    return index_text[span[0]:span[1]] if span else None


def main(argv=None) -> int:
    import config

    args = list(sys.argv[1:] if argv is None else argv)
    if args not in (["--check"], ["--write"]):
        print("usage: build_index.py --check | --write", file=sys.stderr)
        return 2
    wiki = config.wiki_root() / "wiki"
    index = wiki / "index.md"
    if not wiki.is_dir() or not index.is_file():
        print("ERROR: wiki/index.md not found", file=sys.stderr)
        return 2
    index_text = index.read_text(encoding="utf-8")
    catalog = render_catalog(wiki)
    rewritten = apply(index_text, catalog)
    if args == ["--check"]:
        if rewritten == index_text:
            print("CLEAN | index catalog matches page descriptions")
            return 0
        print("DRIFT | index catalog out of date — run scripts/build_index.py --write")
        return 1
    if rewritten != index_text:
        index.write_text(rewritten, encoding="utf-8")
        print("WROTE | wiki/index.md catalog regenerated")
    else:
        print("CLEAN | wiki/index.md already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
